# Goldmark settings Blowfish relies on. Keep cloudcannon.config.yml `markdown:` in step with these.

[goldmark]
  [goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
    [goldmark.parser.attribute]
      block = true
  [goldmark.renderer]
    unsafe = true
  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true
      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
